### ISSUE TITLE
更新版本至 0.10.2

### ISSUE THREAD

**Issue by Jonathan523** [hu3rror/memos-on-fly-build#1]
上游已发布 0.10.2 希望能更新 docker 镜像

**Comment by hu3rror** [comment]
已更新 image。~~不过 fly.io 连接到 docker hub 似乎有网络故障~~，若无法更新，可以将 docker 镜像 pull 到本地 `docker pull hu3rror/memos-fly:latest`，再使用 `flyctl deploy --local-only`

new info: https://community.fly.io/t/deploying-to-fly-via-github-action-failing/10171/18?u=jsierles

**Comment by Jonathan523** [comment]
感谢，其实实在不行还能直接dockerfile部署
